apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-ui-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-ui
  template:
    metadata:
      labels:
        app: admin-ui
    spec:
      containers:
        - name: admin-ui
          image: vladimirkot/admin-ui
---
apiVersion: v1
kind: Service
metadata:
  name: admin-ui-srv
spec:
  selector:
    app: admin-ui
  ports:
    - name: admin-ui
      protocol: TCP
      port: 3001
      targetPort: 3001
